#!/bin/bash
#
# The 'run' performs a simple test that verifies that STI image.
# The main focus here is to excersise the STI scripts.
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
#

IMAGE_NAME=${IMAGE_NAME-ausnimbus/s2i-golang:1.8}
VERSION=${VERSION-"1.8"}
S2I_ARGS=${S2I_ARGS:-""}

TEST_APPS=({print,gowebapp,blueprint})
VERSION_COMMAND="go version"

extra_tests() {
  info 'Testing PRESTISSIMO'
  CONTAINER_ARGS='-e PRESTISSIMO=true' test_application
}

test_dir="$(readlink -zf $(dirname "${BASH_SOURCE[0]}"))"
source ${test_dir}/../common/tests/s2i
