sudo: required
matrix:
  include:
  - services:
    - docker
    env: VARIANTS=default
before_install:
# Install s2i
- |
  go get github.com/openshift/source-to-image
  pushd ${GOPATH}/src/github.com/openshift/source-to-image
  export PATH=$PATH:${GOPATH}/src/github.com/openshift/source-to-image/_output/local/bin/linux/amd64/
  hack/build-go.sh
  popd
script:
- if [ "$TRAVIS_BRANCH" = "master" ]; then export DOCKER_PUSH=true && docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" quay.io; fi
- ./hack/run build
notifications:
  slack:
    secure: Dtb2kj+QEGyDftcAI/NRJIdZGOvLC0RwX9AIWZD/pmdjw9EzAo4W1DIPlW0uFtg/GhxQTXjJcjTPBWbTXsSC7Ca1vfIVDtFH0VH6ar2D9sogt3GYzpQ0qvs7M8EyNI7OSjutLw5GwMtLHDmdL7gsyTzh6EEfCzfOjrOTx03RmFSwMvXaEbQvwAPLiSKkb8yuAakf+8JPL7bkzJcAec7B0BFLOlki29mrrFabpWA0fT212o3gzaQ1uxoHw950DXspcFfkALcaKCnF4Tch3hU86/CAue7Xus5+BWNcxtpd3SPLooMDvULhermQ3Y8YVrBJOscjX+3dzW3SltXDCStMXZqdD7jNJlxYpzmp7oULzKwA/dYHMF6bULlU77Brz7Bi+FEWLBk4jfulFhDGgD9UHVHI9SCTFr08pSefqMQfWyrEpzoJrgjqCM8nTb2YqiTR+O3ych3UO1d3e/xmNvQhiHxAU85XIJxPQsUA8moNP2jK7GIN7JBGCIgHHr5uzfiwPYdzksj7wSsNb+P1lWWqdcGTV1kIaCCfinHfuXNCmTuZwI2WyRtYKIomODGxDtBG16cGBcU1t5a8lo8lx7MmbsLiqBKOgphJEslyDpGzmF9zU1q+MQA5RDQvDPCZbmYKVESBqbln0g3VezuZ5d8EmP21Eh64CUEcNbl4Zk3Yuo8=
env:
  global:
  - secure: gAJ4QrZ/JXG4FjVmwJf04/+V/uvsVV7Q40/8b5JmBH2xMygNf9Z2JwZOMT6QyFw3TlKk9AVPhmhDi8U2n5haSd8qagjMygNNHTxghiwbpauv3gwyHamZa6/fN0/1l+YXAzcz4Odk0w+Fm6p/s2TqX871ueHBkclVIN6fmKgT2bvvOo7UFy1yIhciGDl59nJ525R2HY5y5vnXd4NVHR6VGa9vn6KlXt7eVafQU6aDvHenlXcnd9jxrutIfh7dU0V5HWLjC2ROyC1huk6K/u/3rlsQXTgD09zccZzysda97TdR1aRfSG7wApjNzbwZ6oAin9mq3T/qlgee1bbXw8iYL4ep+bhA1nwTb22YRDYqzwoF8+SI+F7bfo0BwsgM1uqC1LF67XlYVDci5SBK1qndldlgLbabp4Z9dda9SNGYgJ4ghAgPv6X3ao3IxL0Qbmpi6RSmwRwsN06P8yKW/ym2Kiwmrb5V3A5huf8hmZWBm5xUJSCdkeGps1ctMkxzNHH/ykES3Msg8QM9VRGcda+rGQdEMHjouFyHGY2YOcMoFuw29fDdxmExb1DNtDsHNQyEYT34ovFsodkHXBVv7HyvgzFyNUWSzpx6KajBhAldAbNrr45dGIVhgyF0LevMrBraXJ0tSHvAbUX+4Y5NEPjafJ8RpsmewfmBHJYUwW//PYI=
  - secure: Vrz+evzwwwE0puHhhXFZRfaCGHGt6VRwEErlcfkIIBP29Ncp2diT6RYB/mog+IKVP0H77jtmOZdmY24K8rhnu3EOq/w3gPtRguLyDuNrACaNNztEI6wOM0nwATZBoQN5AsbgcJ+zzoRGNfk9ORjEU73n0WCMaYjA06xEttW6/0xKzR747kqeVQ78oTDspnXaIlISakDI4vn1qKdDsFd/tnhO3cR2SlAjNthm3g8WZGMjH7RHY3DHZNt89Dn3EmOz0vU/Uh395A8GC4KONkwc4CI0QU1xyTy8fTCpvE+Py5AzAJst5MCFwwZTPpPJFVqFh/oa6TPoY2p4mqyxnRXz6iT4r+EjLE2eHpA8/p2ldHGRqsqwhFyHHzb9NofeDQCdeXmMa5dV+KuGaTbcviPCSecQ0pGSxVfQsAbFAszMwytWtKt+3zXVG70rtNv5iOvFf0eLgstZSgQxaE+UoW6a4PEgPoE9NBRaKUd+TSFyh29S559rMl2gDHRaV986nIcS5afq6jriCVxhakygvtbqDK0oaWb0naMyNRAgTMt7rV70QirlaC6q5kPQQTblXwQ1zozNK6Ta+QrdUA0zQySgyCp++LXGpc2y54HJksV4U5uQKygivRD/pteH8YZaBAys2X9Aii4/JMLmVYqmmq97+4i0Ehot2BMD6p54vvPrSEI=
