#!/bin/bash

NAME="golang"
DISPLAY_NAME="Golang"
TYPE="s2i"
VARIANT="alpine"
VERSIONS="1.7,1.8"

DOCKER_PUSH=${DOCKER_PUSH:-"false"}

source $(readlink -zf $(dirname "${BASH_SOURCE[0]}"))/../common/hack/run
